### ISSUE TITLE
Where is the "test" folder?

### ISSUE THREAD

**Issue by wmwv** [Professor-G/MicroLIA#16]
The README.md suggest running test scripts in a "test" folder?  I don't see that folder in my checkout from today (SHA: 8e9c7c5).  Where should I look for these tests?

"""
# Test Script

To make sure that the algorithm is working, please run the following test scripts located in the test folder:

test_features
test_classifier
If both test scripts work you are good to go!
"""

**Comment by Professor-G** [comment]
The test folder has been added with the two test scripts as well as the required test data -- this accounts for all the new features included since version 1. Please install the latest stable version of the program via pip, **version 2.6.0**

The Example page in the RTD documentation now includes updated examples. 
Cheers
